CREATE DATABASE IF NOT EXISTS Tasks;
USE Tasks;

CREATE TABLE IF NOT EXISTS Categorie(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS Task(
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    dataInizio DATE DEFAULT CURRENT_DATE,
    dataFine DATE DEFAULT CURRENT_DATE,
    priorita INTEGER DEFAULT 0,
    iDcategoria INTEGER NOT NULL,
    FOREIGN KEY (iDcategoria) REFERENCES Categorie(id),
    completata BOOLEAN DEFAULT FALSE
);